name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: |
          npm ci
          npm run lint
          npm run test:type
          npm test
          npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
